POSTGRES_HOST: 10.203.224.213
POSTGRES_PORT: 5432
POSTGRES_USER_NAME: postgres
POSTGRES_DATABASE_NAME: the_ui
AZURE_APPLICATION_NAME: Forcepoint Behavioral Analytics
USERS_SYNC_TIME_IN_MINUTES: 1
DEFAULT_FBA_PASSWORD: ChangeME
SSO_CONFIG_SCRIPT_PATH: /home/dlo/azure_fba/sso_config_script.sh